Created contact form
alphayowakarindi/My-Portfolio pull request #3
Opened 2022-06-01 18:00 UTC by alphayowakarindi

I've added a contact form in the contact section with HTML and CSS. I've also implemented the form to be able to send data from users on the internet using Formspree, a form backend API and email service for HTML forms

2022-06-01 18:11 UTC, youmari requested changes
Hi @alphayowakarindi , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ Great title and short summary
✔️ No linter error
✔️ Github flow

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-01 18:11 UTC, youmari commented on index.html
> +    <footer id="footer">
- [ ] This is a section so it would be better if you use the `<section>` tag instead of the `<footer>` tag

2022-06-01 18:11 UTC, youmari commented on index.html
> +            <input type="email" name="email" placeholder="natajayanj14@gmail.com" required>
- [ ] it would be better in `placeholder` value instead of n`atajayanj14@gmail.com`change it to `Email` that makes sense

2022-06-01 18:11 UTC, youmari commented on index.html
> +            <button type="submit">Get In Touch</button>
- [ ] it would be better if you implement the button effect on hover and pressed as in the Figma design in order to match the Design

2022-06-01 22:01 UTC, alphayowakarindi commented
@youmari Thank you very much for the feedback to make my code better. I've made all the recommended changes. Cheers!

2022-06-02 02:21 UTC, omarsalem7 requested changes
Hi @alphayowakarindi, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![Almost near](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

 ## Highlights
✔️ All linter checks pass
✔️ Descriptive pull request

 ## Required Changes ♻️
- [x] As the previous reviewer mentioned, please add a hover effect for the button as in Figma template `color-code: #6070FF`

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-02 08:35 UTC, Mre55 approved these changes
**Hi @alphayowakarindi,**

# Status: APPROVED 🏆 🎉 

Your project is complete!  There is nothing else to say other than... it's time to merge it  🚀: 
Congratulations! 🎉 

## To highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- The README is well documented ✅ 
- Linters are working properly ✅ 

<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-02 08:35 UTC, Mre55 commented on style.css
> +    background: #6070ff;
**[OPTIONAL]** Good job 👍 implementing the hover suggested by the previous reviewer. Just to make it look professional add `color: #fff` on the here on the hover style currently on hover the text is not visible.

2022-06-02 08:49 UTC, alphayowakarindi commented on style.css
> +    background: #6070ff;
Hi, nice change advice. I like it with the adjustment. Thank you.

2022-06-02 08:50 UTC, merged