Created desktop version of my portfolio homepage
alphayowakarindi/My-Portfolio pull request #5
Opened 2022-06-03 14:59 UTC by alphayowakarindi

I've created the homepage of my portfolio with HTML and CSS. It has the following sections: Header, Headline, Portfolio list, About me and Contact form in the footer.

2022-06-03 15:32 UTC, Lucas-Masaba requested changes
# Hello @alphayowakarindi  👋 , 

Good job so far! 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

## Highlights 🍾 
- Linter checks passing ✔️ 
- UI looks like that of the Figma 🏄 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 💭 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

- [ ] Please center the "Get In Touch" button as seen in the Figma template 👍 
### Your implementation
![image](https://user-images.githubusercontent.com/45460192/171887699-b24a40fb-71bb-4908-89bb-919da244b31a.png)
### Figma 
![image](https://user-images.githubusercontent.com/45460192/171888047-9c1055e3-9b8b-4b9a-a709-53c134b8f58a.png)

2022-06-03 15:32 UTC, Lucas-Masaba commented on style.css
>  @media (max-width: 600px) {
- [ ] Please add a range to this media query for example 
``` 
@media (max-width: 768px) and (max-width: 1100px) {
    //
    //
    //
}
```
Currently, your design breaks when the browser reaches a certain width because when it passes 600px, the design will break. It currently looks like that in a screenshot below
![image](https://user-images.githubusercontent.com/45460192/171884192-22acd0f9-b07c-4229-aede-65b82ce75317.png)

2022-06-03 17:44 UTC, alphayowakarindi commented on style.css
>  @media (max-width: 600px) {
@Lucas-Masaba Hi, thank you for the suggestions to make my code better. I might be wrong and I stand corrected. 
 Shouldn't this be min-width and max-width? If what you have provided is correct, kindly explain what that does?
``` 
@media (max-width: 768px) and (max-width: 1100px) {
    //
    //
    //
} 
```

2022-06-04 08:15 UTC, muneebulrehman approved these changes
Hi @alphayowakarindi , 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🥳
Congratulations! 🎉 

# Status:  Approved ✔️

## Highlights
- Good follow-up with the previous reviewer
- Good commit history
- Good CSS

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- I recommend making cursor as pointer upon hover on buttons and links.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-04 09:21 UTC, merged